[project]
name = "aioaquacell"
version = "0.0.0"
description = "Asynchronous library to retrieve details of your Aquacell water softener device"
readme = "README.md"
requires-python = ">=3.10,<4"
license = "Apache-2.0"
authors = [{ name = "Jordi Epema", email = "jordi.epema@gmail.com" }]
maintainers = [{ name = "Jordi Epema", email = "jordi.epema@gmail.com" }]
dependencies = [
    "aiohttp>=3.14.1",
    "pycognito>=2024.5.1",
    "boto3>=1.10.49",
    "botocore>=1.13.49",
    "aws-request-signer>=1.0",
]

[project.urls]
Homepage = "https://github.com/Jordi1990/aioaquacell"
Repository = "https://github.com/Jordi1990/aioaquacell"
Documentation = "https://github.com/Jordi1990/aioaquacell"

[tool.poetry]
packages = [
    { include = "aioaquacell" },
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.9"
pre-commit = "^4.5.1"
pre-commit-hooks = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
